baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Site"
theme = "tale"

[menu]
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    title = "Contact"
    url = "/contact/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0